Algoritmo "PROGRAMA1"



Var

 p, q, d, t : real



Inicio


  
  escreval (" Bem -vindo")
  escreval ("Digite preço unitário do produto: ")
  escreva ("Preço unitário: ")
  leia (p)

  
  escreval ("Digite a quantidade comprada: ")
  escreva ("quantidade comprada: ")
  leia (q)

  escreval ("Valor recebido: ")
  escreva ("Dinheiro: ")
  leia (d)
  
  t <- d - (p*q)
  
  escreva ("TROCO = ", t)
  
  
  
Fimalgoritmo