Algoritmo "PROGRAMA1"



Var

 nota1, nota2, media : real



Inicio


  
  escreval (" Bem -vindo")
  escreval
  escreva ("Digite a primeira nota: ")
  leia (nota1)
  
    escreva ("Digite a segunda nota: ")
  leia (nota2)
  
  media <- nota1 + nota2


  escreval ("MEDIA = ", media)
  
        se media < 60  entao
        
           escreva (" REPROVADO ")

        fimse
  
Fimalgoritmo