Algoritmo "crescente"



Var


   x, y : real


Inicio



   escreval (" Bem -vindo")
   escreval

   escreval ("Digite dois números: ")
   leia (x)
   leia (y)

   enquanto x <> y faca
   
      se x > y entao
         escreva ("CRESCENTE")
      senao
         escreval ("DECRESCENTE")
      fimse

      escreval
      escreval ("Digite outro numero:")
      leia (x)
      leia (y)

   fimenquanto




Fimalgoritmo