Algoritmo "media_ponderada"



Var


    i, n : inteiro
    x, a, b, c : real

Inicio


       escreval ("Quantos casos você ai digitar? ")
       leia (n)


      para i de 1 ate n faca
      
           escreval ("Digite o número: ")
           leia (a)
           leia (b)
           leia (c)
           
             x <- (a*2 + b*3 + c*5) / 10

             escreval ("MEDIA = ", x:4:2)
      
      fimpara
       



Fimalgoritmo